name: 'Build AUR Package'
description: 'Build an ArchLinux package in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  pkg-name:
    description: 'ArchLinux package name to build'
    required: true
    default: ""
  preinstallPkgs:
    description: 'packages need install before build, separated by space'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pkg-name }}
