name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */8 * * *'

jobs:
  build:
    strategy:
      matrix:
        repos: [aur/wayfire-git]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}

    - name: Prepare a unique name for Artifacts
      id: prep_artifact_name
      run: |
        if [ "${{ matrix.repos }}" != "" ] ; then
            name="${{ matrix.repos }}"
        fi
        name=$(echo -n "${name##*/}")
        echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}
